[package]
name = "markflow-core"
description = "Markflow parser + PipeAdapter + streaming rewriter"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lol_html = { workspace = true }
thiserror = { workspace = true }
markdown = { workspace = true }
log = { workspace = true }
html-escape = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
once_cell = { workspace = true }

[package.metadata.insta]
review = false
snapshot-path = "tests/snapshots"
