[package]
name = "markflow-napi"
description = "Node bindings for Markflow"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
markflow-core = { path = "../core" }
napi = { workspace = true }
napi-derive = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
