[package]
name = "markflow-napi"
description = "Node bindings for Markflow"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
markflow-core = { path = "../core" }
napi = { version = "3", default-features = false, features = ["napi4", "serde-json"] }
napi-derive = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
napi-build = "2"
