[package]
name = "mdx-hybrid-engine-rust"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["napi4"] }
napi-derive = "2"
mdxjs = "0.2"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true