/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CompileOptions {
  development?: boolean
  jsx?: boolean
  jsxRuntime?: string
  jsxImportSource?: string
  pragma?: string
  pragmaFrag?: string
  pragmaImportSource?: string
}
export interface CompileResult {
  code: string
  map?: string
  timing: number
}
export declare function compileSync(content: string, options?: CompileOptions | undefined | null): CompileResult
export declare function isAvailable(): boolean
